apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: airline-app

  template:
    metadata:
      labels:
        app: airline-app

    spec:
      containers:
      - name: airline-app
        image: gokulkrishna0201/airline:latest
        ports:
        - containerPort: 5000

        env:                      # ✅ MUST be inside container
        - name: DATABASE_URL
          value: "postgresql://username:password@host:5432/dbname"
